name: Build and Release
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_for_linux:
    runs-on: ubuntu-latest
    name: Build for Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: satackey/action-docker-layer-caching@v0.0.8

      - name: Build Docker builder image
        run: docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -f .github/docker/linux/Dockerfile -t builder .

      - name: Build
        run: docker run --rm -e CI -v $(pwd):/app -w /app builder

  build_for_windows:
    runs-on: ubuntu-latest
    name: Build for Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: satackey/action-docker-layer-caching@v0.0.8

      - name: Build Docker builder image
        run: docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -f .github/docker/windows/Dockerfile -t builder .

      - name: Build
        run: docker run --rm -e CI -v $(pwd):/app -w /app builder
